version: "3.9"
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpassword
      POSTGRES_DB: botdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=botdb;Username=botuser;Password=botpassword
      Telegram__Token: "7687765772:AAE8Jkl7Jrb3zSr9NYgTZ1_6AP-jqIjitfk"
    networks:
      - botnet
    command: >
      sh -c "dotnet ef database update && dotnet CurrencyTelegramBot.dll"

volumes:
  pgdata:

networks:
  botnet:
    driver: bridge

